### ISSUE TITLE
 public void onWakeUp(AppData appData) {

### ISSUE THREAD

**Issue by xiaojie111** [OpenInstall/openinstall-cocos2dx-sdk#1]
public void onWakeUp(AppData appData) {这个方法没进去是什么原因

**Comment by wenkiwu** [comment]
你好，onWakeUp未回调，请先确定是否注册了回调监听，其次确保应用是使用openinstall的网页拉起的（推荐使用openinstall后台的测试二维码扫描测试）。如有疑问，请联系官网提供的技术支持，以便得到及时的帮助
